language: python
python:
  - "2.7"
  - "pypy"
addons:
  apt:
    packages:
      - net-tools
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
before_script:
  - mkdir -p ~/.screenly ~/.config/uzbl/
  - cp ansible/roles/screenly/files/uzbl-config ~/.config/uzbl/config-screenly
  - cp ansible/roles/screenly/files/screenly.conf ~/.screenly/
script: nosetests -v -a '!fixme'

sudo: false
