language: python
python:
  - "2.7"
  - "pypy"
addons:
  apt:
    packages:
      - net-tools
install:
  - pip install -r requirements.txt
before_script:
  - mkdir -p ~/.screenly ~/screenly/misc
  - cp misc/screenly.conf ~/.screenly/
  - cp misc/uzbl.rc ~/screenly/misc/
script: nosetests -v
