---

- name: Download rpi-update
  get_url:
    url: https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update
    dest: /usr/bin/rpi-update
    mode: 0755
    owner: root
    group: root
  when: ansible_distribution_release == "wheezy"

- name: Run kernel upgrade
  command: /usr/bin/rpi-update SKIP_WARNING=1
  when: ansible_distribution_release == "wheezy"
  async: 1800
  poll: 5
  register: rpi-update
  tags:
    - system-upgrade
