---

- name: Download rpi-update
  get_url:
    url: https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update
    dest: /usr/bin/rpi-update
    mode: 0755
    owner: root
    group: root
  when: ansible_distribution_release == "wheezy"

- name: Run kernel upgrade
  shell: /usr/bin/rpi-update
  when: ansible_distribution_release == "wheezy"
  environment:
    SKIP_WARNING: 1
  register: rpiupdate
  tags:
    - system-upgrade

- debug: msg="{{ rpiupdate.stdout  }}"
