- name: Install Screenly
  hosts: all
  become: yes

  vars:
    - screenly_user: pi

  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted

    - name: restart-screenly-server
      command: systemctl restart screenly-web.service

    - name: restart-screenly-viewer
      command: systemctl restart screenly-viewer.service

  roles:
    - system
    - network
    - { role: rpi-update, when: is_raspi }
    - screenly
    - splashscreen
    - ssl
