- name: Install Screenly
  hosts: all
  user: pi
  become: yes

  handlers:
    - include: handlers/main.yml

  roles:
    - system
    - network
    - rpi-update
    - screenly
    - splashscreen
    - ssl
